import torch
from torch_geometric.nn import MessagePassing
import torch.nn as nn


class DeepSet_BL(MessagePassing):
    """
    Class for the DeepSet baseline, i.e. use only an action module to predict actions given the states (no passing
    features or feudal architecture).
    """
    def __init__(self, mu, seed=None):
        """
        Args:
            mu: trainable function (action generation).
            seed: model seed
        """
        super().__init__(aggr='add', flow='source_to_target')
        if seed is not None:
            torch.manual_seed(seed)

        self._mu = ActionGen(mu)

    def forward(self, s):
        """
        Args:
            s: workers states with shape [num_workers, limb_obs_size].
        """
        actions = self._mu(s).numpy()

        return actions

    def get_model_num_params(self):
        """
        Return sum of the number of parameters of trainable functions of the DS model.
        """
        num_pars = 0
        num_pars += sum([i.numel() for i in self._mu.state_dict().values()])

        return num_pars

    def get_model_funcs(self):
        """
        Return list of trainable functions of the DS model.
        """
        functions = [self._mu]

        return nn.ModuleList(functions)


class ActionGen(nn.Module):
    def __init__(self, act_net, msg_layers=None):
        super().__init__()
        self.act_network = act_net
        self.msg_layers = msg_layers

    def forward(self, goals, node_idx=None):
        """
        :param goals: goals generated by manager
        :return: actions
        """

        if node_idx is None:
            return self.act_network(goals)

        return self.act_network(goals[node_idx])
