import torch
from torch_geometric.nn import MessagePassing
import torch.nn as nn
import networkx as nx
from torch_geometric.utils import from_networkx


class GNN_BL(MessagePassing):
    """
    Class for the GNN baseline, i.e. use only message-passing features without feudal architecture (only workers).
    """
    def __init__(self, lr, W_1_dim, phi_1, mu, seed=None, cfg_env=None, graph=None):
        """
        Args:
            lr: number of message-passing rounds.
            W_1_dim: list [in_dim, out_dim] for the weight matrix W_1.
            phi_1: list of lists of trainable functions (message functions for agent graphs).
            mu: trainable function (action generation).
            cfg_env: config file.
            graph: generated agent graph.
        """
        super().__init__(aggr='add', flow='source_to_target')
        if seed is not None:
            torch.manual_seed(seed)

        self.cfg_env = cfg_env
        self._Lr = lr
        self.agent_graph = self.generate_agent_graph(graph)

        self._W_1 = nn.Linear(W_1_dim[0], W_1_dim[1], bias=False)
        self._phi_1 = NeighbourFeats(phi_1)
        self._mu = ActionGen(mu)

    def forward(self, s, f=None):
        """
        Args:
            s: workers states.
            f: additional node features.
        """
        if f is not None:
            x = torch.cat([s, f], dim=-1)
        else:
            x = s
        h_wrk = self._W_1(torch.from_numpy(x).float().to(torch.float32))

        for lr in range(self._Lr):
            h_wrk = self._phi_1(h_wrk, self.agent_graph)

        actions = self._mu(h_wrk).numpy()

        return actions

    def generate_agent_graph(self, graph):
        # worker graph
        from networkx import from_numpy_matrix
        agent_graph = from_networkx(from_numpy_matrix(graph.W.toarray())).edge_index

        return agent_graph

    def get_model_num_params(self):
        """
        Return sum of the number of parameters of trainable functions of the GNN model.
        """
        num_pars = 0

        num_pars += sum([i.numel() for i in self._W_1.state_dict().values()])
        num_pars += sum([i.numel() for i in self._mu.state_dict().values()])
        num_pars += sum([i.numel() for i in self._phi_1.state_dict().values()])

        return num_pars

    def get_model_funcs(self):
        """
        Return list of trainable functions of the GNN model.
        """
        functions = []

        functions.append(self._W_1)
        functions.append(self._mu)
        functions.append(self._phi_1)

        return nn.ModuleList(functions)


class NeighbourFeats(MessagePassing):
    def __init__(self, net):
        super().__init__(aggr='add')
        self.message_network = net

    def forward(self, x, edge_index):
        messages = self.propagate(edge_index, x=x)
        return messages

    def message(self, x_i, x_j):
        out = self.message_network(torch.cat([x_i, x_j], dim=1))
        return out


class ActionGen(nn.Module):
    def __init__(self, act_net, msg_layers=None):
        super().__init__()
        self.act_network = act_net
        self.msg_layers = msg_layers

    def forward(self, goals, node_idx=None):
        """
        :param goals: goals generated by manager
        :return: actions
        """

        if node_idx is None:
            return self.act_network(goals)

        return self.act_network(goals[node_idx])
